# Generated by Django 4.2.14 on 2026-04-03 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitekey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inviteactivation',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activations', to='invites.invitekey'),
        ),
        migrations.AddField(
            model_name='inviteactivation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_activations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='inviteactivation',
            unique_together={('key', 'user')},
        ),
    ]
