# Generated by Django 4.2.14 on 2026-04-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('total_broadcasts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'System Stats',
                'verbose_name_plural': 'System Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('tasks_submitted', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('tasks_rejected', models.PositiveIntegerField(default=0)),
                ('earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'User Daily Stats',
                'verbose_name_plural': 'User Daily Stats',
                'ordering': ['-date'],
            },
        ),
    ]
