# Generated by Django 4.2.14 on 2026-04-10 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0004_alter_systemstats_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Дата пропуска')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Зафиксировано в')),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name='Заполнено позднее')),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_missed_days', to=settings.AUTH_USER_MODEL, verbose_name='Кем заполнено')),
            ],
            options={
                'verbose_name': 'Пропущенный день',
                'verbose_name_plural': 'Пропущенные дни',
                'ordering': ['-date'],
            },
        ),
    ]
