# Generated by Django 4.2.14 on 2026-04-21 22:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_globalrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAdSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Дата понедельника этой недели', unique=True, verbose_name='Начало недели (понедельник)')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Рекламные расходы (₽)')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Рекламные расходы (неделя)',
                'verbose_name_plural': 'Рекламные расходы (по неделям)',
                'ordering': ['-week_start'],
            },
        ),
    ]
