"""initial durable Welcome data plane

Revision ID: 0001
Revises:
"""

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def _execute_statements(sql: str) -> None:
    for statement in sql.split(";"):
        if statement.strip():
            op.execute(statement)


def upgrade() -> None:
    _execute_statements(
        """
        CREATE TABLE owner (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          telegram_id BIGINT NOT NULL UNIQUE,
          username VARCHAR(64) NOT NULL DEFAULT '', first_name VARCHAR(128) NOT NULL DEFAULT '',
          last_name VARCHAR(128) NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX ix_owner_telegram_id ON owner (telegram_id);

        CREATE TABLE managed_bot (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          public_id UUID NOT NULL UNIQUE, telegram_id BIGINT NOT NULL UNIQUE,
          username VARCHAR(64) NOT NULL DEFAULT '', display_name VARCHAR(128) NOT NULL,
          token_ciphertext TEXT NOT NULL, key_version INTEGER NOT NULL DEFAULT 1,
          webhook_secret VARCHAR(64) NOT NULL, path_secret VARCHAR(64) NOT NULL,
          is_active BOOLEAN NOT NULL DEFAULT true, welcome_delay_seconds INTEGER NOT NULL DEFAULT 0,
          approval_delay_seconds INTEGER NOT NULL DEFAULT 0, auto_approve BOOLEAN NOT NULL DEFAULT false,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX ix_managed_bot_owner_id ON managed_bot(owner_id);
        CREATE INDEX ix_managed_bot_public_id ON managed_bot(public_id);
        CREATE INDEX ix_managed_bot_telegram_id ON managed_bot(telegram_id);
        CREATE INDEX ix_managed_bot_is_active ON managed_bot(is_active);

        CREATE TABLE channel (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          bot_id BIGINT NOT NULL REFERENCES managed_bot(id) ON DELETE CASCADE,
          telegram_id BIGINT NOT NULL, title VARCHAR(255) NOT NULL, username VARCHAR(64) NOT NULL DEFAULT '',
          is_active BOOLEAN NOT NULL DEFAULT true, can_invite_users BOOLEAN NOT NULL DEFAULT false,
          CONSTRAINT uq_channel_bot_telegram UNIQUE(bot_id, telegram_id)
        );
        CREATE INDEX ix_channel_bot_id ON channel(bot_id);
        CREATE INDEX ix_channel_is_active ON channel(is_active);

        CREATE TABLE welcome_message_version (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          bot_id BIGINT NOT NULL REFERENCES managed_bot(id) ON DELETE CASCADE,
          version INTEGER NOT NULL, author_telegram_id BIGINT NOT NULL, payload JSONB NOT NULL,
          is_active BOOLEAN NOT NULL DEFAULT false, created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_welcome_version UNIQUE(bot_id, version)
        );
        CREATE INDEX ix_welcome_message_version_bot_id ON welcome_message_version(bot_id);
        CREATE INDEX ix_welcome_message_version_is_active ON welcome_message_version(is_active);

        CREATE TABLE welcome_media (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          version_id BIGINT NOT NULL REFERENCES welcome_message_version(id) ON DELETE CASCADE,
          position INTEGER NOT NULL DEFAULT 0, media_type VARCHAR(32) NOT NULL,
          storage_key VARCHAR(500) NOT NULL, original_name VARCHAR(255) NOT NULL DEFAULT '',
          mime_type VARCHAR(128) NOT NULL DEFAULT '', size BIGINT NOT NULL DEFAULT 0
        );
        CREATE INDEX ix_welcome_media_version_id ON welcome_media(version_id);

        CREATE TABLE contact (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          bot_id BIGINT NOT NULL REFERENCES managed_bot(id) ON DELETE CASCADE, telegram_id BIGINT NOT NULL,
          username VARCHAR(64) NOT NULL DEFAULT '', first_name VARCHAR(128) NOT NULL DEFAULT '',
          last_name VARCHAR(128) NOT NULL DEFAULT '', language_code VARCHAR(16) NOT NULL DEFAULT 'unknown',
          delivery_status VARCHAR(16) NOT NULL DEFAULT 'unknown', bot_started BOOLEAN NOT NULL DEFAULT false,
          first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(), last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          last_delivery_at TIMESTAMPTZ, last_error VARCHAR(500) NOT NULL DEFAULT '',
          CONSTRAINT uq_contact_bot_telegram UNIQUE(bot_id, telegram_id)
        );
        CREATE INDEX ix_contact_bot_id ON contact(bot_id);
        CREATE INDEX ix_contact_delivery_status ON contact(delivery_status);

        CREATE TABLE inbox_event (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          source_key VARCHAR(96) NOT NULL, bot_id BIGINT REFERENCES managed_bot(id) ON DELETE CASCADE,
          update_id BIGINT NOT NULL, payload JSONB NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'pending',
          attempts INTEGER NOT NULL DEFAULT 0, available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          lease_owner VARCHAR(64), lease_expires_at TIMESTAMPTZ, last_error VARCHAR(500) NOT NULL DEFAULT '',
          received_at TIMESTAMPTZ NOT NULL DEFAULT now(), processed_at TIMESTAMPTZ,
          CONSTRAINT uq_inbox_source_update UNIQUE(source_key, update_id)
        );
        CREATE INDEX ix_inbox_event_bot_id ON inbox_event(bot_id);
        CREATE INDEX ix_inbox_event_status ON inbox_event(status);
        CREATE INDEX ix_inbox_event_received_at ON inbox_event(received_at);
        CREATE INDEX ix_inbox_claim ON inbox_event(status, available_at, lease_expires_at);

        CREATE TABLE greeting_delivery (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          bot_id BIGINT NOT NULL REFERENCES managed_bot(id) ON DELETE CASCADE,
          channel_id BIGINT NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
          contact_id BIGINT NOT NULL REFERENCES contact(id) ON DELETE CASCADE,
          version_id BIGINT REFERENCES welcome_message_version(id) ON DELETE SET NULL,
          event_key VARCHAR(128) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'scheduled',
          attempts INTEGER NOT NULL DEFAULT 0, due_at TIMESTAMPTZ NOT NULL,
          lease_owner VARCHAR(64), lease_expires_at TIMESTAMPTZ, sent_at TIMESTAMPTZ,
          error VARCHAR(500) NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_delivery_bot_event UNIQUE(bot_id, event_key)
        );
        CREATE INDEX ix_greeting_delivery_bot_id ON greeting_delivery(bot_id);
        CREATE INDEX ix_greeting_delivery_status ON greeting_delivery(status);
        CREATE INDEX ix_greeting_delivery_due_at ON greeting_delivery(due_at);
        CREATE INDEX ix_delivery_claim ON greeting_delivery(status, due_at, lease_expires_at);

        CREATE TABLE join_request (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          bot_id BIGINT NOT NULL REFERENCES managed_bot(id) ON DELETE CASCADE,
          channel_id BIGINT NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
          contact_id BIGINT NOT NULL REFERENCES contact(id) ON DELETE CASCADE,
          telegram_update_id BIGINT NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'pending',
          due_at TIMESTAMPTZ, attempts INTEGER NOT NULL DEFAULT 0, lease_owner VARCHAR(64),
          lease_expires_at TIMESTAMPTZ, error VARCHAR(500) NOT NULL DEFAULT '',
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(), processed_at TIMESTAMPTZ,
          CONSTRAINT uq_join_bot_update UNIQUE(bot_id, telegram_update_id)
        );
        CREATE INDEX ix_join_request_bot_id ON join_request(bot_id);
        CREATE INDEX ix_join_request_status ON join_request(status);
        CREATE INDEX ix_join_request_due_at ON join_request(due_at);

        CREATE TABLE event_log (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          bot_id BIGINT REFERENCES managed_bot(id) ON DELETE CASCADE,
          owner_id BIGINT REFERENCES owner(id) ON DELETE SET NULL,
          event_type VARCHAR(64) NOT NULL, level VARCHAR(16) NOT NULL DEFAULT 'info',
          message VARCHAR(500) NOT NULL, context JSONB NOT NULL DEFAULT '{}'::jsonb,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX ix_event_log_bot_id ON event_log(bot_id);
        CREATE INDEX ix_event_log_owner_id ON event_log(owner_id);
        CREATE INDEX ix_event_log_event_type ON event_log(event_type);
        CREATE INDEX ix_event_log_created_at ON event_log(created_at);
        """
    )


def downgrade() -> None:
    _execute_statements(
        """
        DROP TABLE IF EXISTS event_log;
        DROP TABLE IF EXISTS join_request;
        DROP TABLE IF EXISTS greeting_delivery;
        DROP TABLE IF EXISTS inbox_event;
        DROP TABLE IF EXISTS contact;
        DROP TABLE IF EXISTS welcome_media;
        DROP TABLE IF EXISTS welcome_message_version;
        DROP TABLE IF EXISTS channel;
        DROP TABLE IF EXISTS managed_bot;
        DROP TABLE IF EXISTS owner;
        """
    )
