"""native owner bot drafts

Revision ID: 0007
Revises: 0006
"""

from alembic import op

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def _execute_statements(sql: str) -> None:
    for statement in sql.split(";"):
        if statement.strip():
            op.execute(statement)


def upgrade() -> None:
    _execute_statements(
        """
        CREATE TABLE welcome_draft (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          bot_id BIGINT NOT NULL REFERENCES managed_bot(id) ON DELETE CASCADE,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          media_group_id VARCHAR(128) NOT NULL,
          payload JSONB NOT NULL DEFAULT '{}'::jsonb,
          finalize_at TIMESTAMPTZ NOT NULL,
          finalized_version_id BIGINT REFERENCES welcome_message_version(id) ON DELETE SET NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_welcome_draft_group UNIQUE(bot_id, media_group_id)
        );
        CREATE INDEX ix_welcome_draft_bot_id ON welcome_draft(bot_id);
        CREATE INDEX ix_welcome_draft_owner_id ON welcome_draft(owner_id);
        CREATE INDEX ix_welcome_draft_finalize ON welcome_draft(finalize_at);
        CREATE INDEX ix_welcome_draft_finalized_version_id ON welcome_draft(finalized_version_id);

        CREATE TABLE welcome_draft_media (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          draft_id BIGINT NOT NULL REFERENCES welcome_draft(id) ON DELETE CASCADE,
          telegram_message_id BIGINT NOT NULL,
          media_type VARCHAR(32) NOT NULL,
          storage_key VARCHAR(500) NOT NULL,
          original_name VARCHAR(255) NOT NULL DEFAULT '',
          mime_type VARCHAR(128) NOT NULL DEFAULT '',
          size BIGINT NOT NULL DEFAULT 0,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_welcome_draft_message UNIQUE(draft_id, telegram_message_id)
        );
        CREATE INDEX ix_welcome_draft_media_draft_id ON welcome_draft_media(draft_id);
        """
    )


def downgrade() -> None:
    _execute_statements(
        """
        DROP TABLE IF EXISTS welcome_draft_media;
        DROP TABLE IF EXISTS welcome_draft;
        """
    )
