"""commercial plans, trials and Mini App sessions

Revision ID: 0008
Revises: 0007
"""

from alembic import op

revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def _execute_statements(sql: str) -> None:
    connection = op.get_bind()
    for statement in sql.split(";"):
        if statement.strip():
            connection.exec_driver_sql(statement)


def upgrade() -> None:
    _execute_statements(
        """
        ALTER TABLE owner ADD COLUMN trial_started_at TIMESTAMPTZ;
        ALTER TABLE owner ADD COLUMN trial_ends_at TIMESTAMPTZ;
        CREATE INDEX ix_owner_trial_ends_at ON owner(trial_ends_at);

        CREATE TABLE plan (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          slug VARCHAR(32) NOT NULL,
          display_name VARCHAR(64) NOT NULL,
          entitlements JSONB NOT NULL DEFAULT '{}'::jsonb,
          max_bots INTEGER NOT NULL,
          max_channels INTEGER NOT NULL,
          monthly_delivery_operations INTEGER NOT NULL,
          media_storage_bytes BIGINT NOT NULL,
          price_rub NUMERIC(14,2),
          price_xtr INTEGER,
          referral_base_rub NUMERIC(14,2),
          crypto_pay_enabled BOOLEAN NOT NULL DEFAULT false,
          stars_enabled BOOLEAN NOT NULL DEFAULT false,
          is_sellable BOOLEAN NOT NULL DEFAULT true,
          is_active BOOLEAN NOT NULL DEFAULT true,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT plan_slug_key UNIQUE(slug),
          CONSTRAINT ck_plan_positive_quotas CHECK (
            max_bots > 0 AND max_channels > 0
            AND monthly_delivery_operations > 0 AND media_storage_bytes > 0
          ),
          CONSTRAINT ck_plan_crypto_price CHECK (
            NOT crypto_pay_enabled OR price_rub > 0
          ),
          CONSTRAINT ck_plan_stars_price CHECK (
            NOT stars_enabled OR (price_xtr > 0 AND referral_base_rub > 0)
          )
        );
        CREATE INDEX ix_plan_slug ON plan(slug);
        CREATE INDEX ix_plan_is_active ON plan(is_active);

        INSERT INTO plan (
          slug, display_name, entitlements, max_bots, max_channels,
          monthly_delivery_operations, media_storage_bytes, is_sellable
        ) VALUES
          (
            'trial', 'Business Trial',
            '{"welcome_chains":true,"bulk_assignment":true,"referrals":true,"manuals":true,"tips":true,"rotation":true,"advanced_analytics":true,"exports":true}'::jsonb,
            1, 5, 5000, 1073741824, false
          ),
          (
            'pro', 'Pro',
            '{"welcome_chains":true,"bulk_assignment":true,"referrals":true,"manuals":true,"tips":true,"rotation":false,"advanced_analytics":false,"exports":false}'::jsonb,
            3, 25, 50000, 5368709120, true
          ),
          (
            'business', 'Business',
            '{"welcome_chains":true,"bulk_assignment":true,"referrals":true,"manuals":true,"tips":true,"rotation":true,"advanced_analytics":true,"exports":true}'::jsonb,
            15, 150, 250000, 26843545600, true
          );

        CREATE TABLE subscription (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          plan_id BIGINT NOT NULL REFERENCES plan(id) ON DELETE RESTRICT,
          source VARCHAR(24) NOT NULL,
          status VARCHAR(24) NOT NULL,
          starts_at TIMESTAMPTZ NOT NULL,
          ends_at TIMESTAMPTZ NOT NULL,
          auto_renew BOOLEAN NOT NULL DEFAULT false,
          external_reference VARCHAR(128) NOT NULL DEFAULT '',
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT subscription_owner_id_key UNIQUE(owner_id),
          CONSTRAINT ck_subscription_period CHECK (ends_at > starts_at),
          CONSTRAINT ck_subscription_status CHECK (
            status IN ('trialing','active','past_due','expired','canceled')
          ),
          CONSTRAINT ck_subscription_source CHECK (
            source IN ('trial','crypto_pay','telegram_stars','manual')
          )
        );
        CREATE INDEX ix_subscription_owner_id ON subscription(owner_id);
        CREATE INDEX ix_subscription_plan_id ON subscription(plan_id);
        CREATE INDEX ix_subscription_status ON subscription(status);
        CREATE INDEX ix_subscription_ends_at ON subscription(ends_at);
        CREATE INDEX ix_subscription_access ON subscription(status, ends_at);

        CREATE TABLE feature_flag (
          key VARCHAR(64) PRIMARY KEY,
          enabled BOOLEAN NOT NULL DEFAULT false,
          config JSONB NOT NULL DEFAULT '{}'::jsonb,
          description VARCHAR(255) NOT NULL DEFAULT '',
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        INSERT INTO feature_flag(key, description) VALUES
          ('entitlement_enforcement', 'Pause paid runtime when owner access expires'),
          ('welcome_app_enabled', 'Expose the GramlyHello Mini App'),
          ('commercial_admin_enabled', 'Expose owner-only commercial administration'),
          ('crypto_pay_bot_checkout', 'Offer Crypto Pay in the Telegram owner bot'),
          ('crypto_pay_mini_app_checkout', 'Offer Crypto Pay in the Telegram Mini App'),
          ('telegram_stars_checkout', 'Offer Telegram Stars subscriptions');

        CREATE TABLE web_session (
          id UUID PRIMARY KEY,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          token_hash VARCHAR(64) NOT NULL UNIQUE,
          csrf_hash VARCHAR(64) NOT NULL,
          telegram_auth_date TIMESTAMPTZ NOT NULL,
          expires_at TIMESTAMPTZ NOT NULL,
          revoked_at TIMESTAMPTZ,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX ix_web_session_owner_id ON web_session(owner_id);
        CREATE INDEX ix_web_session_expires_at ON web_session(expires_at);

        CREATE TABLE idempotency_record (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          key VARCHAR(128) NOT NULL,
          request_hash VARCHAR(64) NOT NULL,
          response_status INTEGER,
          response_body JSONB,
          expires_at TIMESTAMPTZ NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_idempotency_owner_key UNIQUE(owner_id, key)
        );
        CREATE INDEX ix_idempotency_record_owner_id ON idempotency_record(owner_id);
        CREATE INDEX ix_idempotency_record_expires_at ON idempotency_record(expires_at);
        """
    )


def downgrade() -> None:
    _execute_statements(
        """
        DROP TABLE IF EXISTS idempotency_record;
        DROP TABLE IF EXISTS web_session;
        DROP TABLE IF EXISTS feature_flag;
        DROP TABLE IF EXISTS subscription;
        DROP TABLE IF EXISTS plan;
        DROP INDEX IF EXISTS ix_owner_trial_ends_at;
        ALTER TABLE owner DROP COLUMN IF EXISTS trial_ends_at;
        ALTER TABLE owner DROP COLUMN IF EXISTS trial_started_at;
        """
    )
