"""versioned content chains and per-operation delivery outbox

Revision ID: 0009
Revises: 0008
"""

from alembic import op

revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def _execute_statements(sql: str) -> None:
    connection = op.get_bind()
    for statement in sql.split(";"):
        if statement.strip():
            connection.exec_driver_sql(statement)


def upgrade() -> None:
    _execute_statements(
        """
        CREATE TABLE content_flow (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          bot_id BIGINT NOT NULL REFERENCES managed_bot(id) ON DELETE CASCADE,
          name VARCHAR(128) NOT NULL,
          kind VARCHAR(16) NOT NULL,
          assignment_mode VARCHAR(16) NOT NULL DEFAULT 'all',
          is_active BOOLEAN NOT NULL DEFAULT true,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_content_flow_bot_kind_name UNIQUE(bot_id, kind, name),
          CONSTRAINT ck_content_flow_kind CHECK (kind IN ('welcome','farewell')),
          CONSTRAINT ck_content_flow_assignment_mode CHECK (
            assignment_mode IN ('all','selected')
          )
        );
        CREATE INDEX ix_content_flow_bot_id ON content_flow(bot_id);
        CREATE INDEX ix_content_flow_kind ON content_flow(kind);
        CREATE INDEX ix_content_flow_is_active ON content_flow(is_active);

        CREATE TABLE content_flow_version (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          flow_id BIGINT NOT NULL REFERENCES content_flow(id) ON DELETE CASCADE,
          version INTEGER NOT NULL,
          status VARCHAR(16) NOT NULL,
          author_telegram_id BIGINT NOT NULL,
          first_delay_seconds INTEGER NOT NULL DEFAULT 0,
          legacy_version_id BIGINT UNIQUE REFERENCES welcome_message_version(id) ON DELETE SET NULL,
          published_at TIMESTAMPTZ,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_content_flow_version UNIQUE(flow_id, version),
          CONSTRAINT ck_content_flow_version_status CHECK (
            status IN ('draft','published','archived')
          ),
          CONSTRAINT ck_content_flow_first_delay CHECK (
            first_delay_seconds BETWEEN 0 AND 86400
          )
        );
        CREATE INDEX ix_content_flow_version_flow_id ON content_flow_version(flow_id);
        CREATE INDEX ix_content_flow_version_status ON content_flow_version(status);
        CREATE UNIQUE INDEX uq_content_flow_published
          ON content_flow_version(flow_id) WHERE status = 'published';
        CREATE UNIQUE INDEX uq_content_flow_draft
          ON content_flow_version(flow_id) WHERE status = 'draft';

        CREATE TABLE content_step (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          version_id BIGINT NOT NULL REFERENCES content_flow_version(id) ON DELETE CASCADE,
          position INTEGER NOT NULL,
          payload JSONB NOT NULL DEFAULT '{}'::jsonb,
          delay_after_seconds INTEGER NOT NULL DEFAULT 0,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_content_step_position UNIQUE(version_id, position),
          CONSTRAINT ck_content_step_position CHECK (position >= 0),
          CONSTRAINT ck_content_step_delay CHECK (
            delay_after_seconds BETWEEN 0 AND 86400
          )
        );
        CREATE INDEX ix_content_step_version_id ON content_step(version_id);

        CREATE TABLE content_attachment (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          step_id BIGINT NOT NULL REFERENCES content_step(id) ON DELETE CASCADE,
          position INTEGER NOT NULL,
          media_type VARCHAR(32) NOT NULL,
          storage_key VARCHAR(500) NOT NULL,
          original_name VARCHAR(255) NOT NULL DEFAULT '',
          mime_type VARCHAR(128) NOT NULL DEFAULT '',
          size BIGINT NOT NULL DEFAULT 0,
          payload JSONB NOT NULL DEFAULT '{}'::jsonb,
          CONSTRAINT uq_content_attachment_position UNIQUE(step_id, position),
          CONSTRAINT ck_content_attachment_position CHECK (position >= 0)
        );
        CREATE INDEX ix_content_attachment_step_id ON content_attachment(step_id);

        CREATE TABLE content_keyboard (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          step_id BIGINT NOT NULL REFERENCES content_step(id) ON DELETE CASCADE,
          kind VARCHAR(16) NOT NULL,
          settings JSONB NOT NULL DEFAULT '{}'::jsonb,
          CONSTRAINT content_keyboard_step_id_key UNIQUE(step_id),
          CONSTRAINT ck_content_keyboard_kind CHECK (kind IN ('inline','reply'))
        );
        CREATE INDEX ix_content_keyboard_step_id ON content_keyboard(step_id);

        CREATE TABLE content_keyboard_button (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          keyboard_id BIGINT NOT NULL REFERENCES content_keyboard(id) ON DELETE CASCADE,
          row INTEGER NOT NULL,
          position INTEGER NOT NULL,
          text VARCHAR(128) NOT NULL,
          action_type VARCHAR(16) NOT NULL,
          value VARCHAR(1024) NOT NULL,
          style VARCHAR(16) NOT NULL DEFAULT 'default',
          CONSTRAINT uq_content_keyboard_button_position UNIQUE(keyboard_id, row, position),
          CONSTRAINT ck_content_keyboard_button_position CHECK (row >= 0 AND position >= 0),
          CONSTRAINT ck_content_keyboard_button_action CHECK (
            action_type IN ('url','callback','text')
          ),
          CONSTRAINT ck_content_keyboard_button_style CHECK (
            style IN ('default','primary','success','danger')
          )
        );
        CREATE INDEX ix_content_keyboard_button_keyboard_id
          ON content_keyboard_button(keyboard_id);

        CREATE TABLE flow_channel_assignment (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          flow_id BIGINT NOT NULL REFERENCES content_flow(id) ON DELETE CASCADE,
          channel_id BIGINT NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_flow_channel_assignment UNIQUE(flow_id, channel_id)
        );
        CREATE INDEX ix_flow_channel_assignment_flow_id ON flow_channel_assignment(flow_id);
        CREATE INDEX ix_flow_channel_assignment_channel_id ON flow_channel_assignment(channel_id);

        CREATE TABLE flow_delivery (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          bot_id BIGINT NOT NULL REFERENCES managed_bot(id) ON DELETE CASCADE,
          channel_id BIGINT NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
          contact_id BIGINT NOT NULL REFERENCES contact(id) ON DELETE CASCADE,
          version_id BIGINT NOT NULL REFERENCES content_flow_version(id) ON DELETE RESTRICT,
          event_key VARCHAR(128) NOT NULL,
          status VARCHAR(16) NOT NULL DEFAULT 'scheduled',
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          completed_at TIMESTAMPTZ,
          CONSTRAINT uq_flow_delivery_bot_event UNIQUE(bot_id, event_key),
          CONSTRAINT ck_flow_delivery_status CHECK (
            status IN ('scheduled','processing','completed','partial','failed','cancelled')
          )
        );
        CREATE INDEX ix_flow_delivery_bot_id ON flow_delivery(bot_id);
        CREATE INDEX ix_flow_delivery_channel_id ON flow_delivery(channel_id);
        CREATE INDEX ix_flow_delivery_contact_id ON flow_delivery(contact_id);
        CREATE INDEX ix_flow_delivery_version_id ON flow_delivery(version_id);
        CREATE INDEX ix_flow_delivery_status ON flow_delivery(status);

        CREATE TABLE delivery_operation (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          flow_delivery_id BIGINT NOT NULL REFERENCES flow_delivery(id) ON DELETE CASCADE,
          step_id BIGINT NOT NULL REFERENCES content_step(id) ON DELETE RESTRICT,
          depends_on_operation_id BIGINT REFERENCES delivery_operation(id) ON DELETE RESTRICT,
          position INTEGER NOT NULL,
          operation_type VARCHAR(32) NOT NULL,
          payload JSONB NOT NULL DEFAULT '{}'::jsonb,
          media JSONB NOT NULL DEFAULT '[]'::jsonb,
          status VARCHAR(16) NOT NULL DEFAULT 'scheduled',
          attempts INTEGER NOT NULL DEFAULT 0,
          due_at TIMESTAMPTZ NOT NULL,
          lease_owner VARCHAR(64),
          lease_expires_at TIMESTAMPTZ,
          sent_at TIMESTAMPTZ,
          error VARCHAR(500) NOT NULL DEFAULT '',
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_delivery_operation_position UNIQUE(flow_delivery_id, position),
          CONSTRAINT ck_delivery_operation_position CHECK (position >= 0),
          CONSTRAINT ck_delivery_operation_status CHECK (
            status IN ('scheduled','processing','retry','sent','failed','cancelled')
          )
        );
        CREATE INDEX ix_delivery_operation_flow_delivery_id
          ON delivery_operation(flow_delivery_id);
        CREATE INDEX ix_delivery_operation_step_id ON delivery_operation(step_id);
        CREATE INDEX ix_delivery_operation_depends_on_operation_id
          ON delivery_operation(depends_on_operation_id);
        CREATE INDEX ix_delivery_operation_status ON delivery_operation(status);
        CREATE INDEX ix_delivery_operation_due_at ON delivery_operation(due_at);
        CREATE INDEX ix_delivery_operation_claim
          ON delivery_operation(status, due_at, lease_expires_at);

        INSERT INTO content_flow (bot_id, name, kind, assignment_mode, is_active)
        SELECT DISTINCT version.bot_id, 'Приветствие', 'welcome', 'all', true
        FROM welcome_message_version AS version;

        INSERT INTO content_flow_version (
          flow_id, version, status, author_telegram_id, first_delay_seconds,
          legacy_version_id, published_at, created_at
        )
        SELECT flow.id,
               legacy.version,
               CASE WHEN legacy.is_active THEN 'published' ELSE 'archived' END,
               legacy.author_telegram_id,
               bot.welcome_delay_seconds,
               legacy.id,
               CASE WHEN legacy.is_active THEN now() ELSE NULL END,
               legacy.created_at
        FROM welcome_message_version AS legacy
        JOIN content_flow AS flow
          ON flow.bot_id = legacy.bot_id AND flow.kind = 'welcome'
        JOIN managed_bot AS bot ON bot.id = legacy.bot_id;

        INSERT INTO content_step (version_id, position, payload, delay_after_seconds, created_at)
        SELECT version.id, 0, legacy.payload, 0, legacy.created_at
        FROM content_flow_version AS version
        JOIN welcome_message_version AS legacy ON legacy.id = version.legacy_version_id;

        INSERT INTO content_attachment (
          step_id, position, media_type, storage_key, original_name, mime_type, size, payload
        )
        SELECT step.id,
               media.position,
               media.media_type,
               media.storage_key,
               media.original_name,
               media.mime_type,
               media.size,
               '{}'::jsonb
        FROM content_step AS step
        JOIN content_flow_version AS version ON version.id = step.version_id
        JOIN welcome_media AS media ON media.version_id = version.legacy_version_id;
        """
    )


def downgrade() -> None:
    _execute_statements(
        """
        DROP TABLE IF EXISTS delivery_operation;
        DROP TABLE IF EXISTS flow_delivery;
        DROP TABLE IF EXISTS flow_channel_assignment;
        DROP TABLE IF EXISTS content_keyboard_button;
        DROP TABLE IF EXISTS content_keyboard;
        DROP TABLE IF EXISTS content_attachment;
        DROP TABLE IF EXISTS content_step;
        DROP TABLE IF EXISTS content_flow_version;
        DROP TABLE IF EXISTS content_flow;
        """
    )
