"""replace trials and Pro with Free/Business advertising model

Revision ID: 0010
Revises: 0009
"""

from alembic import op

revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def _execute_statements(sql: str) -> None:
    connection = op.get_bind()
    for statement in sql.split(";"):
        if statement.strip():
            connection.exec_driver_sql(statement)


def upgrade() -> None:
    _execute_statements(
        """
        ALTER TABLE subscription DROP CONSTRAINT ck_subscription_period;
        ALTER TABLE subscription DROP CONSTRAINT ck_subscription_status;
        ALTER TABLE subscription DROP CONSTRAINT ck_subscription_source;
        ALTER TABLE subscription ALTER COLUMN ends_at DROP NOT NULL;

        UPDATE plan
        SET slug = 'free',
            display_name = 'Free',
            entitlements = '{"welcome_chains":true,"bulk_assignment":true,"referrals":true,"manuals":true,"tips":true,"advanced_analytics":true,"exports":true,"rotation":false,"ad_free":false}'::jsonb,
            max_bots = 15,
            max_channels = 150,
            monthly_delivery_operations = 250000,
            media_storage_bytes = 26843545600,
            price_rub = NULL,
            price_xtr = NULL,
            referral_base_rub = NULL,
            crypto_pay_enabled = false,
            stars_enabled = false,
            is_sellable = true,
            is_active = true,
            updated_at = now()
        WHERE slug = 'trial';

        UPDATE subscription
        SET plan_id = (SELECT id FROM plan WHERE slug = 'free'),
            source = 'free',
            status = 'active',
            starts_at = now(),
            ends_at = NULL,
            auto_renew = false,
            external_reference = '',
            updated_at = now()
        WHERE plan_id = (SELECT id FROM plan WHERE slug = 'pro');

        DELETE FROM plan WHERE slug = 'pro';

        UPDATE subscription
        SET source = 'free',
            status = 'active',
            starts_at = LEAST(starts_at, now()),
            ends_at = NULL,
            auto_renew = false,
            external_reference = '',
            updated_at = now()
        WHERE plan_id = (SELECT id FROM plan WHERE slug = 'free');

        UPDATE plan
        SET entitlements = '{"welcome_chains":true,"bulk_assignment":true,"referrals":true,"manuals":true,"tips":true,"advanced_analytics":true,"exports":true,"rotation":true,"ad_free":true}'::jsonb,
            max_bots = 15,
            max_channels = 150,
            monthly_delivery_operations = 250000,
            media_storage_bytes = 26843545600,
            is_sellable = true,
            is_active = true,
            updated_at = now()
        WHERE slug = 'business';

        INSERT INTO subscription (
          owner_id, plan_id, source, status, starts_at, ends_at, auto_renew
        )
        SELECT owner.id, plan.id, 'free', 'active', now(), NULL, false
        FROM owner CROSS JOIN plan
        WHERE plan.slug = 'free'
          AND NOT EXISTS (
            SELECT 1 FROM subscription WHERE subscription.owner_id = owner.id
          );

        ALTER TABLE subscription ADD CONSTRAINT ck_subscription_period CHECK (
          (source = 'free' AND ends_at IS NULL)
          OR (source <> 'free' AND ends_at > starts_at)
        );
        ALTER TABLE subscription ADD CONSTRAINT ck_subscription_status CHECK (
          status IN ('active','past_due','expired','canceled')
        );
        ALTER TABLE subscription ADD CONSTRAINT ck_subscription_source CHECK (
          source IN ('free','crypto_pay','telegram_stars','manual')
        );

        CREATE TABLE ad_creative (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(128) NOT NULL,
          text TEXT NOT NULL,
          entities JSONB NOT NULL DEFAULT '[]'::jsonb,
          cta_text VARCHAR(64) NOT NULL DEFAULT '',
          cta_url VARCHAR(2048) NOT NULL DEFAULT '',
          weight INTEGER NOT NULL DEFAULT 1,
          is_active BOOLEAN NOT NULL DEFAULT true,
          created_by_telegram_id BIGINT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT ck_ad_creative_weight CHECK (weight BETWEEN 1 AND 1000),
          CONSTRAINT ck_ad_creative_cta_pair CHECK (
            (cta_text = '' AND cta_url = '') OR (cta_text <> '' AND cta_url <> '')
          )
        );
        CREATE INDEX ix_ad_creative_is_active ON ad_creative(is_active);

        INSERT INTO ad_creative(name, text, cta_text, cta_url, weight)
        VALUES (
          'GramlyHello · default',
          'Приветствие отправлено с помощью GramlyHello',
          'Подключить GramlyHello',
          'https://gramly.tech',
          1
        );

        CREATE TABLE ad_impression (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          public_token UUID NOT NULL,
          creative_id BIGINT NOT NULL REFERENCES ad_creative(id) ON DELETE RESTRICT,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          bot_id BIGINT NOT NULL REFERENCES managed_bot(id) ON DELETE CASCADE,
          channel_id BIGINT NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
          contact_id BIGINT NOT NULL REFERENCES contact(id) ON DELETE CASCADE,
          flow_delivery_id BIGINT NOT NULL REFERENCES flow_delivery(id) ON DELETE CASCADE,
          operation_id BIGINT REFERENCES delivery_operation(id) ON DELETE SET NULL,
          status VARCHAR(16) NOT NULL DEFAULT 'scheduled',
          destination_url VARCHAR(2048) NOT NULL DEFAULT '',
          click_count INTEGER NOT NULL DEFAULT 0,
          selected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          shown_at TIMESTAMPTZ,
          first_clicked_at TIMESTAMPTZ,
          last_clicked_at TIMESTAMPTZ,
          error VARCHAR(500) NOT NULL DEFAULT '',
          CONSTRAINT ad_impression_flow_delivery_id_key UNIQUE(flow_delivery_id),
          CONSTRAINT ad_impression_operation_id_key UNIQUE(operation_id),
          CONSTRAINT ck_ad_impression_status CHECK (
            status IN ('scheduled','sent','failed','cancelled')
          ),
          CONSTRAINT ck_ad_impression_click_count CHECK (click_count >= 0)
        );
        CREATE UNIQUE INDEX ix_ad_impression_public_token ON ad_impression(public_token);
        CREATE INDEX ix_ad_impression_creative_id ON ad_impression(creative_id);
        CREATE INDEX ix_ad_impression_owner_id ON ad_impression(owner_id);
        CREATE INDEX ix_ad_impression_bot_id ON ad_impression(bot_id);
        CREATE INDEX ix_ad_impression_channel_id ON ad_impression(channel_id);
        CREATE INDEX ix_ad_impression_contact_id ON ad_impression(contact_id);
        CREATE INDEX ix_ad_impression_flow_delivery_id ON ad_impression(flow_delivery_id);
        CREATE INDEX ix_ad_impression_operation_id ON ad_impression(operation_id);
        CREATE INDEX ix_ad_impression_status ON ad_impression(status);
        CREATE INDEX ix_ad_impression_shown_at ON ad_impression(shown_at);
        CREATE INDEX ix_ad_impression_first_clicked_at ON ad_impression(first_clicked_at);
        """
    )


def downgrade() -> None:
    _execute_statements(
        """
        DROP TABLE IF EXISTS ad_impression;
        DROP TABLE IF EXISTS ad_creative;
        ALTER TABLE subscription DROP CONSTRAINT ck_subscription_period;
        ALTER TABLE subscription DROP CONSTRAINT ck_subscription_status;
        ALTER TABLE subscription DROP CONSTRAINT ck_subscription_source;
        UPDATE subscription SET ends_at = now() + interval '14 days' WHERE ends_at IS NULL;
        ALTER TABLE subscription ALTER COLUMN ends_at SET NOT NULL;
        UPDATE plan SET slug = 'trial', display_name = 'Business Trial', is_sellable = false
        WHERE slug = 'free';
        UPDATE subscription SET source = 'trial', status = 'trialing'
        WHERE plan_id = (SELECT id FROM plan WHERE slug = 'trial');
        ALTER TABLE subscription ADD CONSTRAINT ck_subscription_period CHECK (ends_at > starts_at);
        ALTER TABLE subscription ADD CONSTRAINT ck_subscription_status CHECK (
          status IN ('trialing','active','past_due','expired','canceled')
        );
        ALTER TABLE subscription ADD CONSTRAINT ck_subscription_source CHECK (
          source IN ('trial','crypto_pay','telegram_stars','manual')
        );
        """
    )
