"""farewell events, rotation pool and attributed conversions

Revision ID: 0011
Revises: 0010
"""

from alembic import op

revision = "0011"
down_revision = "0010"
branch_labels = None
depends_on = None


def _execute_statements(sql: str) -> None:
    connection = op.get_bind()
    for statement in sql.split(";"):
        if statement.strip():
            connection.exec_driver_sql(statement)


def upgrade() -> None:
    _execute_statements(
        """
        ALTER TABLE flow_delivery DROP CONSTRAINT ck_flow_delivery_status;
        ALTER TABLE flow_delivery ADD CONSTRAINT ck_flow_delivery_status CHECK (
          status IN ('scheduled','processing','completed','partial','failed','cancelled','unreachable')
        );

        CREATE TABLE channel_membership (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          channel_id BIGINT NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
          contact_id BIGINT NOT NULL REFERENCES contact(id) ON DELETE CASCADE,
          status VARCHAR(16) NOT NULL,
          last_update_id BIGINT NOT NULL,
          joined_at TIMESTAMPTZ,
          left_at TIMESTAMPTZ,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_channel_membership_contact UNIQUE(channel_id, contact_id),
          CONSTRAINT ck_channel_membership_status CHECK (status IN ('active','left'))
        );
        CREATE INDEX ix_channel_membership_channel_id ON channel_membership(channel_id);
        CREATE INDEX ix_channel_membership_contact_id ON channel_membership(contact_id);
        CREATE INDEX ix_channel_membership_status ON channel_membership(status);

        CREATE TABLE departure_event (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          bot_id BIGINT NOT NULL REFERENCES managed_bot(id) ON DELETE CASCADE,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          channel_id BIGINT NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
          contact_id BIGINT NOT NULL REFERENCES contact(id) ON DELETE CASCADE,
          telegram_update_id BIGINT NOT NULL,
          reason VARCHAR(16) NOT NULL,
          farewell_delivery_id BIGINT UNIQUE REFERENCES flow_delivery(id) ON DELETE SET NULL,
          occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_departure_bot_update UNIQUE(bot_id, telegram_update_id),
          CONSTRAINT ck_departure_reason CHECK (reason IN ('left','kicked'))
        );
        CREATE INDEX ix_departure_event_bot_id ON departure_event(bot_id);
        CREATE INDEX ix_departure_event_owner_id ON departure_event(owner_id);
        CREATE INDEX ix_departure_event_channel_id ON departure_event(channel_id);
        CREATE INDEX ix_departure_event_contact_id ON departure_event(contact_id);

        CREATE TABLE rotation_channel (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          bot_id BIGINT NOT NULL REFERENCES managed_bot(id) ON DELETE CASCADE,
          channel_id BIGINT NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
          is_enabled BOOLEAN NOT NULL DEFAULT true,
          is_priority BOOLEAN NOT NULL DEFAULT false,
          invite_link VARCHAR(512) NOT NULL DEFAULT '',
          invite_link_name VARCHAR(64) NOT NULL DEFAULT 'Gramly rotation',
          last_verified_at TIMESTAMPTZ,
          last_error VARCHAR(500) NOT NULL DEFAULT '',
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT rotation_channel_channel_id_key UNIQUE(channel_id)
        );
        CREATE INDEX ix_rotation_channel_owner_id ON rotation_channel(owner_id);
        CREATE INDEX ix_rotation_channel_bot_id ON rotation_channel(bot_id);
        CREATE INDEX ix_rotation_channel_channel_id ON rotation_channel(channel_id);
        CREATE INDEX ix_rotation_channel_is_enabled ON rotation_channel(is_enabled);
        CREATE INDEX ix_rotation_channel_is_priority ON rotation_channel(is_priority);
        CREATE UNIQUE INDEX uq_rotation_channel_invite_link
          ON rotation_channel(invite_link) WHERE invite_link <> '';

        INSERT INTO rotation_channel(owner_id, bot_id, channel_id, is_enabled)
        SELECT managed_bot.owner_id, channel.bot_id, channel.id, true
        FROM channel JOIN managed_bot ON managed_bot.id = channel.bot_id
        WHERE channel.is_active = true
        ON CONFLICT (channel_id) DO NOTHING;

        CREATE TABLE rotation_recommendation (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          departure_id BIGINT NOT NULL REFERENCES departure_event(id) ON DELETE CASCADE,
          status VARCHAR(16) NOT NULL DEFAULT 'scheduled',
          attempts INTEGER NOT NULL DEFAULT 0,
          due_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          lease_owner VARCHAR(64),
          lease_expires_at TIMESTAMPTZ,
          sent_at TIMESTAMPTZ,
          error VARCHAR(500) NOT NULL DEFAULT '',
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT rotation_recommendation_departure_id_key UNIQUE(departure_id),
          CONSTRAINT ck_rotation_recommendation_status CHECK (
            status IN ('scheduled','processing','retry','sent','failed','unreachable','ineligible')
          )
        );
        CREATE INDEX ix_rotation_recommendation_departure_id ON rotation_recommendation(departure_id);
        CREATE INDEX ix_rotation_recommendation_status ON rotation_recommendation(status);
        CREATE INDEX ix_rotation_recommendation_claim
          ON rotation_recommendation(status, due_at, lease_expires_at);

        CREATE TABLE rotation_impression (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          recommendation_id BIGINT NOT NULL REFERENCES rotation_recommendation(id) ON DELETE CASCADE,
          source_owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          destination_owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          destination_channel_id BIGINT NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
          telegram_user_id BIGINT NOT NULL,
          invite_link_snapshot VARCHAR(512) NOT NULL,
          shown_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_rotation_impression_destination UNIQUE(recommendation_id, destination_channel_id)
        );
        CREATE INDEX ix_rotation_impression_recommendation_id ON rotation_impression(recommendation_id);
        CREATE INDEX ix_rotation_impression_source_owner_id ON rotation_impression(source_owner_id);
        CREATE INDEX ix_rotation_impression_destination_owner_id ON rotation_impression(destination_owner_id);
        CREATE INDEX ix_rotation_impression_destination_channel_id ON rotation_impression(destination_channel_id);
        CREATE INDEX ix_rotation_impression_telegram_user_id ON rotation_impression(telegram_user_id);

        CREATE TABLE rotation_conversion (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          impression_id BIGINT NOT NULL UNIQUE REFERENCES rotation_impression(id) ON DELETE CASCADE,
          destination_channel_id BIGINT NOT NULL REFERENCES channel(id) ON DELETE CASCADE,
          telegram_user_id BIGINT NOT NULL,
          telegram_update_id BIGINT NOT NULL,
          converted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_rotation_conversion_user_channel UNIQUE(telegram_user_id, destination_channel_id)
        );
        CREATE INDEX ix_rotation_conversion_destination_channel_id ON rotation_conversion(destination_channel_id);
        CREATE INDEX ix_rotation_conversion_telegram_user_id ON rotation_conversion(telegram_user_id);
        """
    )


def downgrade() -> None:
    _execute_statements(
        """
        DROP TABLE IF EXISTS rotation_conversion;
        DROP TABLE IF EXISTS rotation_impression;
        DROP TABLE IF EXISTS rotation_recommendation;
        DROP TABLE IF EXISTS rotation_channel;
        DROP TABLE IF EXISTS departure_event;
        DROP TABLE IF EXISTS channel_membership;
        ALTER TABLE flow_delivery DROP CONSTRAINT ck_flow_delivery_status;
        UPDATE flow_delivery SET status = 'failed' WHERE status = 'unreachable';
        ALTER TABLE flow_delivery ADD CONSTRAINT ck_flow_delivery_status CHECK (
          status IN ('scheduled','processing','completed','partial','failed','cancelled')
        );
        """
    )
