"""billing, referral ledger and withdrawals

Revision ID: 0012
Revises: 0011
"""

from alembic import op

revision = "0012"
down_revision = "0011"
branch_labels = None
depends_on = None


def _execute_statements(sql: str) -> None:
    connection = op.get_bind()
    for statement in sql.split(";"):
        if statement.strip():
            connection.exec_driver_sql(statement)


def upgrade() -> None:
    _execute_statements(
        """
        CREATE TABLE referral_code (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          code VARCHAR(48) NOT NULL,
          is_active BOOLEAN NOT NULL DEFAULT true,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT referral_code_owner_id_key UNIQUE(owner_id),
          CONSTRAINT referral_code_code_key UNIQUE(code)
        );
        CREATE INDEX ix_referral_code_owner_id ON referral_code(owner_id);
        CREATE INDEX ix_referral_code_code ON referral_code(code);

        CREATE TABLE referral_attribution (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          referrer_owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          referred_owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          code_snapshot VARCHAR(48) NOT NULL,
          status VARCHAR(16) NOT NULL DEFAULT 'candidate',
          attributed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          first_paid_at TIMESTAMPTZ,
          commission_ends_at TIMESTAMPTZ,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT referral_attribution_referred_owner_id_key UNIQUE(referred_owner_id),
          CONSTRAINT ck_referral_not_self CHECK (referrer_owner_id <> referred_owner_id),
          CONSTRAINT ck_referral_status CHECK (status IN ('candidate','active','inactive'))
        );
        CREATE INDEX ix_referral_attribution_referrer_owner_id ON referral_attribution(referrer_owner_id);
        CREATE INDEX ix_referral_attribution_referred_owner_id ON referral_attribution(referred_owner_id);
        CREATE INDEX ix_referral_attribution_status ON referral_attribution(status);
        CREATE INDEX ix_referral_attribution_commission_ends_at ON referral_attribution(commission_ends_at);

        CREATE TABLE payment (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          checkout_token UUID NOT NULL,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          plan_id BIGINT NOT NULL REFERENCES plan(id) ON DELETE RESTRICT,
          provider VARCHAR(24) NOT NULL,
          provider_invoice_id VARCHAR(128),
          status VARCHAR(16) NOT NULL DEFAULT 'created',
          amount_rub NUMERIC(14,2) NOT NULL,
          original_amount NUMERIC(28,10),
          original_currency VARCHAR(16) NOT NULL DEFAULT 'RUB',
          paid_asset VARCHAR(16),
          exchange_rate_rub NUMERIC(28,10),
          provider_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
          invoice_url VARCHAR(1024) NOT NULL DEFAULT '',
          period_days INTEGER NOT NULL DEFAULT 30,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          paid_at TIMESTAMPTZ,
          refunded_at TIMESTAMPTZ,
          CONSTRAINT payment_checkout_token_key UNIQUE(checkout_token),
          CONSTRAINT uq_payment_provider_invoice UNIQUE(provider, provider_invoice_id),
          CONSTRAINT ck_payment_provider CHECK (provider IN ('crypto_pay','telegram_stars','manual')),
          CONSTRAINT ck_payment_status CHECK (status IN ('created','paid','expired','refunded','failed')),
          CONSTRAINT ck_payment_amount_rub CHECK (amount_rub > 0)
        );
        CREATE INDEX ix_payment_owner_id ON payment(owner_id);
        CREATE INDEX ix_payment_plan_id ON payment(plan_id);
        CREATE INDEX ix_payment_provider ON payment(provider);
        CREATE INDEX ix_payment_status ON payment(status);
        CREATE INDEX ix_payment_paid_at ON payment(paid_at);

        CREATE TABLE payment_event (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          provider VARCHAR(24) NOT NULL,
          event_key VARCHAR(128) NOT NULL,
          payload_hash VARCHAR(64) NOT NULL,
          status VARCHAR(16) NOT NULL DEFAULT 'received',
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          processed_at TIMESTAMPTZ,
          CONSTRAINT uq_payment_event_provider_key UNIQUE(provider, event_key)
        );
        CREATE INDEX ix_payment_event_provider ON payment_event(provider);

        CREATE TABLE subscription_reminder (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          subscription_id BIGINT NOT NULL REFERENCES subscription(id) ON DELETE CASCADE,
          days_before INTEGER NOT NULL,
          due_at TIMESTAMPTZ NOT NULL,
          status VARCHAR(16) NOT NULL DEFAULT 'pending',
          attempts INTEGER NOT NULL DEFAULT 0,
          last_error VARCHAR(500) NOT NULL DEFAULT '',
          sent_at TIMESTAMPTZ,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_subscription_reminder_day UNIQUE(subscription_id, days_before),
          CONSTRAINT ck_subscription_reminder_day CHECK (days_before IN (7,3,1)),
          CONSTRAINT ck_subscription_reminder_status CHECK (
            status IN ('pending','processing','retry','sent','failed')
          )
        );
        CREATE INDEX ix_subscription_reminder_subscription_id ON subscription_reminder(subscription_id);
        CREATE INDEX ix_subscription_reminder_due_at ON subscription_reminder(due_at);
        CREATE INDEX ix_subscription_reminder_claim ON subscription_reminder(status, due_at);

        CREATE TABLE withdrawal (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          public_id UUID NOT NULL,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          requested_rub NUMERIC(14,2) NOT NULL,
          payout_asset VARCHAR(16) NOT NULL DEFAULT 'USDT',
          payout_amount NUMERIC(28,10),
          exchange_rate_rub NUMERIC(28,10),
          recipient_telegram_id BIGINT NOT NULL,
          spend_id VARCHAR(64) NOT NULL,
          status VARCHAR(16) NOT NULL DEFAULT 'requested',
          provider_transfer_id VARCHAR(128) NOT NULL DEFAULT '',
          attempts INTEGER NOT NULL DEFAULT 0,
          available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          last_error VARCHAR(500) NOT NULL DEFAULT '',
          rejection_reason VARCHAR(500) NOT NULL DEFAULT '',
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          processed_at TIMESTAMPTZ,
          CONSTRAINT withdrawal_public_id_key UNIQUE(public_id),
          CONSTRAINT withdrawal_spend_id_key UNIQUE(spend_id),
          CONSTRAINT ck_withdrawal_minimum CHECK (requested_rub >= 1000),
          CONSTRAINT ck_withdrawal_status CHECK (
            status IN ('requested','processing','retry','paid','rejected','failed')
          )
        );
        CREATE INDEX ix_withdrawal_owner_id ON withdrawal(owner_id);
        CREATE INDEX ix_withdrawal_status ON withdrawal(status);

        CREATE TABLE financial_ledger_entry (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE RESTRICT,
          payment_id BIGINT REFERENCES payment(id) ON DELETE RESTRICT,
          withdrawal_id BIGINT REFERENCES withdrawal(id) ON DELETE RESTRICT,
          entry_type VARCHAR(24) NOT NULL,
          amount_rub NUMERIC(14,2) NOT NULL,
          rate_percent NUMERIC(5,2),
          reason VARCHAR(500) NOT NULL DEFAULT '',
          metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT ck_ledger_entry_type CHECK (
            entry_type IN ('commission','reserve','payout','reserve_release','refund','adjustment')
          ),
          CONSTRAINT ck_ledger_nonzero CHECK (amount_rub <> 0),
          CONSTRAINT uq_ledger_owner_payment_type UNIQUE(owner_id, payment_id, entry_type),
          CONSTRAINT uq_ledger_withdrawal_type UNIQUE(withdrawal_id, entry_type)
        );
        CREATE INDEX ix_financial_ledger_entry_owner_id ON financial_ledger_entry(owner_id);
        CREATE INDEX ix_financial_ledger_entry_payment_id ON financial_ledger_entry(payment_id);
        CREATE INDEX ix_financial_ledger_entry_withdrawal_id ON financial_ledger_entry(withdrawal_id);
        CREATE INDEX ix_financial_ledger_entry_entry_type ON financial_ledger_entry(entry_type);
        CREATE INDEX ix_ledger_owner_created ON financial_ledger_entry(owner_id, created_at);

        """
    )
    op.execute(
        """
        CREATE FUNCTION reject_financial_ledger_mutation() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'financial ledger entries are immutable';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER financial_ledger_immutable
          BEFORE UPDATE OR DELETE ON financial_ledger_entry
          FOR EACH ROW EXECUTE FUNCTION reject_financial_ledger_mutation()
        """
    )


def downgrade() -> None:
    _execute_statements(
        """
        DROP TRIGGER IF EXISTS financial_ledger_immutable ON financial_ledger_entry;
        DROP FUNCTION IF EXISTS reject_financial_ledger_mutation();
        DROP TABLE IF EXISTS financial_ledger_entry;
        DROP TABLE IF EXISTS withdrawal;
        DROP TABLE IF EXISTS subscription_reminder;
        DROP TABLE IF EXISTS payment_event;
        DROP TABLE IF EXISTS payment;
        DROP TABLE IF EXISTS referral_attribution;
        DROP TABLE IF EXISTS referral_code;
        """
    )
