"""learning manuals, announcements and contextual tips

Revision ID: 0013
Revises: 0012
"""

from alembic import op

revision = "0013"
down_revision = "0012"
branch_labels = None
depends_on = None


def _execute_statements(sql: str) -> None:
    connection = op.get_bind()
    for statement in sql.split(";"):
        if statement.strip():
            connection.exec_driver_sql(statement)


def upgrade() -> None:
    _execute_statements(
        """
        CREATE TABLE manual (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          slug VARCHAR(64) NOT NULL,
          title VARCHAR(160) NOT NULL,
          telegraph_url VARCHAR(2048) NOT NULL,
          description TEXT NOT NULL DEFAULT '',
          is_onboarding BOOLEAN NOT NULL DEFAULT false,
          is_active BOOLEAN NOT NULL DEFAULT true,
          sort_order INTEGER NOT NULL DEFAULT 0,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT manual_slug_key UNIQUE(slug)
        );
        CREATE INDEX ix_manual_slug ON manual(slug);
        CREATE INDEX ix_manual_is_onboarding ON manual(is_onboarding);
        CREATE INDEX ix_manual_is_active ON manual(is_active);

        CREATE TABLE manual_section (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          manual_id BIGINT NOT NULL REFERENCES manual(id) ON DELETE CASCADE,
          slug VARCHAR(64) NOT NULL,
          title VARCHAR(160) NOT NULL,
          section_url VARCHAR(2048) NOT NULL,
          sort_order INTEGER NOT NULL DEFAULT 0,
          is_active BOOLEAN NOT NULL DEFAULT true,
          CONSTRAINT uq_manual_section_slug UNIQUE(manual_id, slug)
        );
        CREATE INDEX ix_manual_section_manual_id ON manual_section(manual_id);
        CREATE INDEX ix_manual_section_is_active ON manual_section(is_active);

        CREATE TABLE contextual_help (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          feature_key VARCHAR(64) NOT NULL,
          title VARCHAR(160) NOT NULL,
          body TEXT NOT NULL DEFAULT '',
          manual_id BIGINT REFERENCES manual(id) ON DELETE SET NULL,
          section_id BIGINT REFERENCES manual_section(id) ON DELETE SET NULL,
          is_active BOOLEAN NOT NULL DEFAULT true,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT contextual_help_feature_key_key UNIQUE(feature_key)
        );
        CREATE INDEX ix_contextual_help_feature_key ON contextual_help(feature_key);
        CREATE INDEX ix_contextual_help_manual_id ON contextual_help(manual_id);
        CREATE INDEX ix_contextual_help_section_id ON contextual_help(section_id);
        CREATE INDEX ix_contextual_help_is_active ON contextual_help(is_active);

        CREATE TABLE announcement (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title VARCHAR(160) NOT NULL,
          body TEXT NOT NULL,
          entities JSONB NOT NULL DEFAULT '[]'::jsonb,
          audience VARCHAR(16) NOT NULL DEFAULT 'all',
          starts_at TIMESTAMPTZ NOT NULL,
          ends_at TIMESTAMPTZ,
          is_active BOOLEAN NOT NULL DEFAULT true,
          priority INTEGER NOT NULL DEFAULT 0,
          button_text VARCHAR(64) NOT NULL DEFAULT '',
          button_url VARCHAR(2048) NOT NULL DEFAULT '',
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT ck_announcement_audience CHECK (audience IN ('all','free','business')),
          CONSTRAINT ck_announcement_period CHECK (ends_at IS NULL OR ends_at > starts_at)
        );
        CREATE INDEX ix_announcement_audience ON announcement(audience);
        CREATE INDEX ix_announcement_starts_at ON announcement(starts_at);
        CREATE INDEX ix_announcement_ends_at ON announcement(ends_at);
        CREATE INDEX ix_announcement_is_active ON announcement(is_active);

        CREATE TABLE owner_notification (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          announcement_id BIGINT REFERENCES announcement(id) ON DELETE CASCADE,
          kind VARCHAR(24) NOT NULL,
          dedupe_key VARCHAR(128) NOT NULL,
          sequence INTEGER NOT NULL DEFAULT 0,
          payload JSONB NOT NULL DEFAULT '{}'::jsonb,
          status VARCHAR(16) NOT NULL DEFAULT 'pending',
          attempts INTEGER NOT NULL DEFAULT 0,
          due_at TIMESTAMPTZ NOT NULL,
          lease_owner VARCHAR(64),
          lease_expires_at TIMESTAMPTZ,
          last_error VARCHAR(500) NOT NULL DEFAULT '',
          sent_at TIMESTAMPTZ,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_owner_notification_dedupe UNIQUE(owner_id, dedupe_key),
          CONSTRAINT ck_owner_notification_kind CHECK (kind IN ('onboarding','announcement')),
          CONSTRAINT ck_owner_notification_status CHECK (
            status IN ('pending','processing','retry','sent','failed')
          )
        );
        CREATE INDEX ix_owner_notification_owner_id ON owner_notification(owner_id);
        CREATE INDEX ix_owner_notification_announcement_id ON owner_notification(announcement_id);
        CREATE INDEX ix_owner_notification_kind ON owner_notification(kind);
        CREATE INDEX ix_owner_notification_status ON owner_notification(status);
        CREATE INDEX ix_owner_notification_due_at ON owner_notification(due_at);
        CREATE INDEX ix_owner_notification_claim
          ON owner_notification(status, due_at, lease_expires_at);

        CREATE TABLE tip (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          feature_key VARCHAR(64) NOT NULL,
          text TEXT NOT NULL,
          entities JSONB NOT NULL DEFAULT '[]'::jsonb,
          sort_order INTEGER NOT NULL DEFAULT 0,
          is_active BOOLEAN NOT NULL DEFAULT true,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_tip_feature_order UNIQUE(feature_key, sort_order)
        );
        CREATE INDEX ix_tip_feature_key ON tip(feature_key);
        CREATE INDEX ix_tip_is_active ON tip(is_active);

        CREATE TABLE tip_view_state (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          feature_key VARCHAR(64) NOT NULL,
          last_tip_id BIGINT REFERENCES tip(id) ON DELETE SET NULL,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT uq_tip_view_owner_feature UNIQUE(owner_id, feature_key)
        );
        CREATE INDEX ix_tip_view_state_owner_id ON tip_view_state(owner_id);

        CREATE TABLE tip_session (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          public_id UUID NOT NULL,
          owner_id BIGINT NOT NULL REFERENCES owner(id) ON DELETE CASCADE,
          feature_key VARCHAR(64) NOT NULL,
          tip_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
          current_index INTEGER NOT NULL DEFAULT 0,
          expires_at TIMESTAMPTZ NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          CONSTRAINT tip_session_public_id_key UNIQUE(public_id)
        );
        CREATE INDEX ix_tip_session_owner_id ON tip_session(owner_id);
        CREATE INDEX ix_tip_session_feature_key ON tip_session(feature_key);
        CREATE INDEX ix_tip_session_expires_at ON tip_session(expires_at);

        INSERT INTO feature_flag(key, enabled, config, description)
        VALUES (
          'bot_inline_ui',
          true,
          '{"premium_emoji":{"help":"5368324170671202286","guide":"5368324170671202286","important":"5368324170671202286"}}'::jsonb,
          'Inline button colors and configurable Premium Emoji icons'
        )
        ON CONFLICT (key) DO NOTHING;

        INSERT INTO contextual_help(feature_key, title, body) VALUES
          ('home', 'Центр помощи GramlyHello', 'Выберите нужный раздел в интерфейсе. Подсказки меняются, а подробные инструкции подключаются владельцем через Telegraph.'),
          ('bots', 'Подключение бота', 'Создайте бота в BotFather, передайте GramlyHello токен и добавьте клиентского бота администратором канала.'),
          ('flows', 'Цепочки сообщений', 'Соберите черновик, проверьте предпросмотр и только после этого опубликуйте неизменяемую версию.'),
          ('rotation', 'Ротация каналов', 'Ротация доступна на Business. До семи собственных каналов можно сделать приоритетными.'),
          ('auto_approve', 'Автопринятие заявок', 'Бот должен быть администратором с правом приглашать пользователей. Задержка принятия настраивается отдельно.')
        ON CONFLICT (feature_key) DO NOTHING;

        INSERT INTO tip(feature_key, text, sort_order) VALUES
          ('home', 'Начните с одного тестового канала и проверьте весь путь новым Telegram-аккаунтом.', 10),
          ('home', 'Перед запуском проверьте, что у клиентского бота включены необходимые права администратора.', 20),
          ('bots', 'Не пересылайте токен бота людям: GramlyHello хранит его только в зашифрованном виде.', 10),
          ('bots', 'После изменения прав бота нажмите «Проверить подключение», чтобы обновить состояние.', 20),
          ('flows', 'Сначала отправьте себе предпросмотр: уже доставленные части цепочки при retry повторно не отправляются.', 10),
          ('flows', 'Короткая первая задержка обычно воспринимается естественнее мгновенного сообщения.', 20),
          ('rotation', 'Приоритетные каналы показываются первыми, остальные места заполняются без дублей.', 10),
          ('rotation', 'В статистику подписки попадают только вступления по invite link после реального показа.', 20),
          ('auto_approve', 'Если заявок много, небольшая задержка помогает сгладить нагрузку без потери событий.', 10),
          ('auto_approve', 'Отключение автопринятия сохраняет отложенные заявки — они не теряются.', 20)
        ON CONFLICT (feature_key, sort_order) DO NOTHING;
        """
    )


def downgrade() -> None:
    _execute_statements(
        """
        DELETE FROM feature_flag WHERE key = 'bot_inline_ui';
        DROP TABLE IF EXISTS tip_session;
        DROP TABLE IF EXISTS tip_view_state;
        DROP TABLE IF EXISTS tip;
        DROP TABLE IF EXISTS owner_notification;
        DROP TABLE IF EXISTS announcement;
        DROP TABLE IF EXISTS contextual_help;
        DROP TABLE IF EXISTS manual_section;
        DROP TABLE IF EXISTS manual;
        """
    )
