apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gramly-staging
nameSuffix: -staging

resources:
  - ../../../base/welcome-migrations

labels:
  - pairs:
      gramly.tech/environment: staging
    includeSelectors: false
