# Generated by Django 4.2.14 on 2026-06-26 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_submitted', 'Не подан'), ('pending', 'Ожидает проверки'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('revision', 'На доработке'), ('overdue', 'Просрочен')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('text_content', models.TextField(blank=True, verbose_name='Текст отчёта')),
                ('telegram_file_id', models.CharField(blank=True, help_text='ID файла в Telegram (если отчёт — документ/фото)', max_length=255, verbose_name='Telegram file_id')),
                ('file_type', models.CharField(blank=True, help_text='document / photo / text', max_length=20, verbose_name='Тип файла')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('period_label', models.CharField(blank=True, help_text="Например: '25 мая 2026'", max_length=100, verbose_name='Период')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отчёт сотрудника',
                'verbose_name_plural': 'Отчёты сотрудников',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Шаблон отчёта')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_template', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Шаблон отчёта',
                'verbose_name_plural': 'Шаблоны отчётов',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('auto', 'Автоматический (просрочка)'), ('manual', 'Ручной')], db_index=True, max_length=10, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма штрафа')),
                ('reason', models.CharField(max_length=500, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает подтверждения'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('disputed', 'Оспаривается'), ('deleted', 'Удалён')], db_index=True, default='created', max_length=20, verbose_name='Статус')),
                ('dispute_comment', models.TextField(blank=True, verbose_name='Комментарий при оспаривании')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('bot_notification_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='null для автоматических штрафов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_penalties', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='control.employeereport', verbose_name='Связанный отчёт')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_penalties', to=settings.AUTH_USER_MODEL, verbose_name='Принял решение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Базовая ставка')),
                ('bonus_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ставка премирования')),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ставка штрафов')),
                ('other_info', models.TextField(blank=True, verbose_name='Прочие показатели')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_kpi_settings', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_settings', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Настройки KPI',
                'verbose_name_plural': 'Настройки KPI',
            },
        ),
        migrations.CreateModel(
            name='KPIDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='kpi_documents/', verbose_name='KPI-документ (.docx)')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_kpi_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_document', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'KPI-документ',
                'verbose_name_plural': 'KPI-документы',
            },
        ),
        migrations.CreateModel(
            name='ControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_report_penalty_amount', models.DecimalField(decimal_places=2, default=0, help_text='Сумма штрафа, автоматически начисляемого за неподанный отчёт', max_digits=12, verbose_name='Штраф за просрочку отчёта')),
                ('report_deadline_hour', models.PositiveSmallIntegerField(default=23, help_text='Час по московскому времени, после которого отчёт считается просроченным', verbose_name='Час дедлайна отчёта (МСК)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Настройки Контроль-бота',
                'verbose_name_plural': 'Настройки Контроль-бота',
            },
        ),
    ]
