# Generated by Django 4.2.14 on 2026-06-28 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0003_report_system_overhaul'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'ordering': ['name'], 'verbose_name': 'Шаблон отчёта', 'verbose_name_plural': 'Шаблоны отчётов'},
        ),
        migrations.AlterField(
            model_name='controlsettings',
            name='late_report_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Штраф за просрочку отчёта'),
        ),
        migrations.AlterField(
            model_name='controlsettings',
            name='report_deadline_hour',
            field=models.PositiveSmallIntegerField(default=23, verbose_name='Час дедлайна отчёта (МСК)'),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='period_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='status',
            field=models.CharField(choices=[('not_submitted', 'Не подан'), ('pending', 'Ожидает проверки'), ('on_moderation', 'На модерации'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('revision', 'На доработке'), ('overdue', 'Просрочен'), ('resubmitted', 'Повторно отправлен')], db_index=True, default='on_moderation', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='telegram_file_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram file_id'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_penalties', to=settings.AUTH_USER_MODEL, verbose_name='Назначил'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('pending', 'Активен'), ('accepted', 'Подтверждён'), ('rejected', 'Отменён'), ('disputed', 'Оспаривается'), ('deleted', 'Удалён')], db_index=True, default='created', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='content',
            field=models.TextField(blank=True, verbose_name='Шаблон (устар.)'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='correction_deadline_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Сколько часов даётся на повторную подачу после отклонения', verbose_name='Срок исправления (часов)'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='notification_times',
            field=models.JSONField(default=list, help_text='Список строк "HH:MM", до 3 штук', verbose_name='Времена напоминаний'),
        ),
    ]
