# Generated by Django 4.2.14 on 2026-07-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_employeereport_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadlinenotificationlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
