# Generated by Django 4.2.14 on 2026-07-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_report_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereport',
            name='deadline_at',
            field=models.DateTimeField(blank=True, help_text='Рассчитан из шаблона в момент создания; не изменяется при смене дедлайна шаблона', null=True, verbose_name='Дедлайн отчёта'),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='status',
            field=models.CharField(choices=[('not_submitted', 'Не подан'), ('pending', 'Ожидает проверки'), ('on_moderation', 'На модерации'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('revision', 'На доработке'), ('overdue', 'Просрочен'), ('resubmitted', 'Повторно отправлен'), ('updated', 'Обновлён')], db_index=True, default='on_moderation', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='employeereport',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='moderationhistory',
            name='cycle',
            field=models.PositiveSmallIntegerField(default=1, help_text='Номер цикла подача → решение (инкрементируется при каждой повторной подаче)', verbose_name='Цикл модерации'),
        ),
    ]
