# Generated by Django 4.2.14 on 2026-04-03 19:55

import apps.invites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Invite Activation',
                'verbose_name_plural': 'Invite Activations',
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='InviteKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=apps.invites.models._generate_key, max_length=64, unique=True)),
                ('label', models.CharField(blank=True, help_text='Internal label for admin reference', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Invite Key',
                'verbose_name_plural': 'Invite Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
