# Generated by Django 4.2.14 on 2026-04-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inviteactivation',
            options={'ordering': ['-activated_at'], 'verbose_name': 'Активация инвайта', 'verbose_name_plural': 'Активации инвайтов'},
        ),
        migrations.AlterModelOptions(
            name='invitekey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Инвайт-ключ', 'verbose_name_plural': 'Инвайт-ключи'},
        ),
    ]
