# Generated by Django 4.2.14 on 2026-08-04 11:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import secrets
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('can_invite_users', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('language_code', models.CharField(blank=True, default='unknown', max_length=16)),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('unknown', 'Трансформер')], default='unknown', max_length=16)),
                ('delivery_status', models.CharField(choices=[('unknown', 'Не проверен'), ('live', 'Живой'), ('dead', 'Мёртвый')], db_index=True, default='unknown', max_length=16)),
                ('bot_started', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ManagedBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('display_name', models.CharField(max_length=128)),
                ('token_ciphertext', models.TextField()),
                ('webhook_secret', models.CharField(default=secrets.token_urlsafe, max_length=64)),
                ('path_secret', models.CharField(default=secrets.token_urlsafe, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('webhook_configured', models.BooleanField(default=False)),
                ('welcome_delay_seconds', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2592000)])),
                ('approval_delay_seconds', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2592000)])),
                ('auto_approve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('guide_completed', models.BooleanField(default=False)),
                ('guide_step', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeMessageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('author_telegram_id', models.BigIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='welcome_bots.welcomemessage')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.AddField(
            model_name='welcomemessage',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for', to='welcome_bots.welcomemessageversion'),
        ),
        migrations.AddField(
            model_name='welcomemessage',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_message', to='welcome_bots.managedbot'),
        ),
        migrations.CreateModel(
            name='WelcomeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('media_type', models.CharField(max_length=32)),
                ('storage_key', models.CharField(max_length=500)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('size', models.BigIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='welcome_bots.welcomemessageversion')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProcessedUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_updates', to='welcome_bots.managedbot')),
            ],
        ),
        migrations.AddField(
            model_name='managedbot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='welcome_bots.owner'),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_update_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('scheduled', 'Запланирована'), ('approved', 'Принята'), ('cancelled', 'Отменена'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16)),
                ('delay_snapshot_seconds', models.PositiveIntegerField(default=0)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='welcome_bots.managedbot')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='welcome_bots.channel')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='welcome_bots.contact')),
            ],
        ),
        migrations.CreateModel(
            name='GreetingDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], db_index=True, default='scheduled', max_length=16)),
                ('delay_snapshot_seconds', models.PositiveIntegerField(default=0)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='welcome_bots.managedbot')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='welcome_bots.channel')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='welcome_bots.contact')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='welcome_bots.welcomemessageversion')),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('level', models.CharField(default='info', max_length=16)),
                ('message', models.CharField(max_length=500)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='welcome_bots.managedbot')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='welcome_bots.owner')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='welcome_bots.managedbot'),
        ),
        migrations.AddField(
            model_name='channel',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='welcome_bots.managedbot'),
        ),
        migrations.AddConstraint(
            model_name='welcomemessageversion',
            constraint=models.UniqueConstraint(fields=('message', 'version'), name='welcome_unique_message_version'),
        ),
        migrations.AddConstraint(
            model_name='processedupdate',
            constraint=models.UniqueConstraint(fields=('bot', 'update_id'), name='welcome_unique_processed_update'),
        ),
        migrations.AddIndex(
            model_name='managedbot',
            index=models.Index(fields=['owner', 'is_active'], name='welcome_bot_owner_i_4bb2ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(fields=('bot', 'telegram_update_id'), name='welcome_unique_join_update'),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'scheduled'))), fields=('channel', 'contact'), name='welcome_one_open_join_request'),
        ),
        migrations.AddIndex(
            model_name='greetingdelivery',
            index=models.Index(fields=['status', 'due_at'], name='welcome_bot_status_2bc69c_idx'),
        ),
        migrations.AddConstraint(
            model_name='greetingdelivery',
            constraint=models.UniqueConstraint(fields=('bot', 'event_key'), name='welcome_unique_greeting_event'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['bot', 'delivery_status'], name='welcome_bot_bot_id_63f0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['bot', 'language_code'], name='welcome_bot_bot_id_bee485_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['bot', 'gender'], name='welcome_bot_bot_id_e9c67c_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('bot', 'telegram_id'), name='welcome_unique_bot_contact'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['bot', 'is_active'], name='welcome_bot_bot_id_b70034_idx'),
        ),
        migrations.AddConstraint(
            model_name='channel',
            constraint=models.UniqueConstraint(fields=('bot', 'telegram_id'), name='welcome_unique_bot_channel'),
        ),
    ]
