# Generated by Django 4.2.14 on 2026-08-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_group_id', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_drafts', to='welcome_bots.managedbot')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_drafts', to='welcome_bots.owner')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeDraftMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.BigIntegerField()),
                ('media_type', models.CharField(max_length=32)),
                ('storage_key', models.CharField(max_length=500)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='welcome_bots.welcomedraft')),
            ],
            options={
                'ordering': ('telegram_message_id', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='welcomedraftmedia',
            constraint=models.UniqueConstraint(fields=('draft', 'telegram_message_id'), name='welcome_unique_draft_message'),
        ),
        migrations.AddConstraint(
            model_name='welcomedraft',
            constraint=models.UniqueConstraint(fields=('bot', 'media_group_id'), name='welcome_unique_media_group_draft'),
        ),
    ]
