# Generated by Django 4.2.14 on 2026-04-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='work_url',
            field=models.URLField(blank=True, help_text='Рабочая ссылка, выставляется администратором', max_length=500),
        ),
    ]
