# Generated by Django 4.2.14 on 2026-04-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_work_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attracted_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество привлечённых людей, выставляется администратором вручную'),
        ),
    ]
