# Generated by Django 4.2.14 on 2026-04-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_attracted_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ставка за прямых подписчиков (руб. за человека), выставляется администратором', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ставка за подписчиков рефералов (руб. за человека), выставляется администратором', max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='attracted_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество привлечённых подписчиков (прямые), выставляется администратором вручную'),
        ),
    ]
