# Generated by Django 4.2.14 on 2026-06-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_metrics_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('curator', 'Curator'), ('worker', 'Worker'), ('accountant', 'Бухгалтер')], db_index=True, default='worker', max_length=20),
        ),
    ]
