# Generated by Django 4.2.14 on 2026-04-04 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма (руб.)')),
                ('method', models.CharField(choices=[('cryptobot', 'CryptoBot'), ('usdt_trc20', 'USDT TRC20')], max_length=20, verbose_name='Способ выплаты')),
                ('details', models.CharField(help_text='@username для CryptoBot или адрес кошелька для USDT TRC20', max_length=255, verbose_name='Реквизиты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('approved', 'Исполнена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('admin_notifications', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на вывод',
                'verbose_name_plural': 'Заявки на вывод',
                'ordering': ['-created_at'],
            },
        ),
    ]
