# Generated by Django 4.2.14 on 2026-06-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Создана'), ('processing', 'В обработке'), ('receipt_sent', 'Чек отправлен'), ('approved', 'Выполнена'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
