apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gramly-welcome

resources:
  - ../../../base/welcome-migrations

labels:
  - pairs:
      gramly.tech/environment: production
    includeSelectors: false
