# Generated by Django 4.2.14 on 2026-06-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('accountant', 'Бухгалтер'), ('worker', 'Сотрудник'), ('curator', 'Куратор'), ('anonymous', 'Аноним')], db_index=True, default='anonymous', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned')], db_index=True, default='active', max_length=20),
        ),
    ]
