# Generated by Django 4.2.14 on 2026-04-14 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_worklink_seed_from_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Принята'), ('rejected', 'Отклонена')], db_index=True, default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Опциональный текст, который пользователь отправил вместе с заявкой', verbose_name='Сообщение от кандидата')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notifications', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на вступление',
                'verbose_name_plural': 'Заявки на вступление',
                'ordering': ['-created_at'],
            },
        ),
    ]
