apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gramly-platform-alerts.yaml
  - gramly-platform-dashboard.yaml
  - gramly-welcome-alerts.yaml
  - gramly-welcome-dashboard.yaml
  - rbac.yaml
  - routes.yaml
  - tls.yaml
