replicaCount: 1

config:
  existingSecret: observability-oauth2-proxy
  configFile: |-
    provider = "oidc"
    provider_display_name = "Gramly SSO"
    oidc_issuer_url = "https://auth.gramly.tech/application/o/observability/"
    redirect_url = "https://cluster.gramly.tech/oauth2/callback"
    upstreams = ["http://headlamp.observability.svc.cluster.local:80/"]
    email_domains = ["*"]
    scope = "openid profile email entitlements"
    allowed_groups = ["authentik Admins"]
    pass_access_token = false
    pass_authorization_header = false
    pass_user_headers = true
    set_xauthrequest = true
    reverse_proxy = false
    cookie_secure = true
    cookie_samesite = "strict"
    cookie_expire = "8h"
    cookie_refresh = "1h"
    silence_ping_logging = true

extraArgs:
  code-challenge-method: S256
  skip-provider-button: "true"
  whitelist-domain: .gramly.tech

service: {type: ClusterIP, portNumber: 80}
podDisruptionBudget: {enabled: false}
resources:
  requests: {cpu: 25m, memory: 64Mi}
  limits: {cpu: 300m, memory: 192Mi}
