apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../crm-web
  - ../crm-background
  - ../public-web

labels:
  - pairs:
      app.kubernetes.io/part-of: gramly-platform
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
