apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: avyaroslavskiy@miem.hse.ru
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: gramly-public
                namespace: traefik-public
                kind: Gateway
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: avyaroslavskiy@miem.hse.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-account
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: gramly-public
                namespace: traefik-public
                kind: Gateway
