apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: gramly-platform
      app.kubernetes.io/component: database-migration
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
