apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gramly-public
  namespace: traefik-public
  labels:
    gramly.tech/controller: public
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  gatewayClassName: gramly-public
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gramly.tech/contour: public
    - name: auth-https
      hostname: auth.gramly.tech
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: auth-gramly-tech-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gramly.tech/contour: public
    - name: vpn-https
      hostname: vpn.gramly.tech
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: vpn-gramly-tech-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gramly.tech/contour: public
    - name: hello-https
      hostname: hello.gramly.tech
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: hello-gramly-tech-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gramly.tech/contour: public
