# Generated by Django 4.2.14 on 2026-08-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramowner",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
