#!/usr/bin/env bash
set -euo pipefail

if [[ -z "${KUBECONFIG:-}" ]]; then
  echo "KUBECONFIG is not set; refusing to use an implicit cluster context." >&2
  exit 1
fi

kubectl exec -n identity deployment/authentik-server -c server -- ak shell -c \
  "from authentik.flows.models import Flow, FlowStageBinding; from authentik.policies.expression.models import ExpressionPolicy; from authentik.policies.models import PolicyBinding; from authentik.stages.prompt.models import Prompt, PromptStage; from authentik.stages.user_write.models import UserWriteStage; flow=Flow.objects.get(slug='default-authentication-flow'); prompt=PromptStage.objects.get(name='default-password-change-prompt'); write=UserWriteStage.objects.get(name='default-password-change-write'); check,_=ExpressionPolicy.objects.update_or_create(name='gramly-onboarding-password-reset-check',defaults={'expression':'user = request.context.get(\"pending_user\")\nreturn bool(user and user.attributes.get(\"reset_password\") is True)'}); clear,_=ExpressionPolicy.objects.update_or_create(name='gramly-onboarding-password-reset-clear',defaults={'expression':'user = request.context.get(\"pending_user\")\nif not user or user.attributes.get(\"reset_password\") is not True:\n    return False\nuser.attributes[\"reset_password\"] = False\nreturn True'}); prompt_binding,_=FlowStageBinding.objects.update_or_create(target=flow,stage=prompt,defaults={'order':25,'evaluate_on_plan':True,'re_evaluate_policies':False}); write_binding,_=FlowStageBinding.objects.update_or_create(target=flow,stage=write,defaults={'order':26,'evaluate_on_plan':True,'re_evaluate_policies':False}); PolicyBinding.objects.update_or_create(target=prompt_binding,policy=check,defaults={'enabled':True,'order':0,'negate':False,'timeout':30}); PolicyBinding.objects.update_or_create(target=write_binding,policy=clear,defaults={'enabled':True,'order':0,'negate':False,'timeout':30}); email_prompt,_=PromptStage.objects.update_or_create(name='gramly-onboarding-email-prompt'); email_prompt.fields.set([Prompt.objects.get(name='default-user-settings-field-email')]); email_write,_=UserWriteStage.objects.update_or_create(name='gramly-onboarding-email-write',defaults={'user_creation_mode':'never_create'}); email_check,_=ExpressionPolicy.objects.update_or_create(name='gramly-onboarding-email-required',defaults={'expression':'user = request.context.get(\"pending_user\")\nreturn bool(user and not (user.email or \"\").strip())'}); email_prompt_binding,_=FlowStageBinding.objects.update_or_create(target=flow,stage=email_prompt,defaults={'order':27,'evaluate_on_plan':True,'re_evaluate_policies':False}); email_write_binding,_=FlowStageBinding.objects.update_or_create(target=flow,stage=email_write,defaults={'order':28,'evaluate_on_plan':True,'re_evaluate_policies':False}); PolicyBinding.objects.update_or_create(target=email_prompt_binding,policy=email_check,defaults={'enabled':True,'order':0,'negate':False,'timeout':30}); PolicyBinding.objects.update_or_create(target=email_write_binding,policy=email_check,defaults={'enabled':True,'order':0,'negate':False,'timeout':30}); print('GRAMLY_RESULT password_reset_on_login=true email_required_on_login=true')" \
  2>&1 | grep 'GRAMLY_RESULT password_reset_on_login=true' >/dev/null

echo "Forced password reset and required email on first login are configured."
