# Generated by Django 4.2.14 on 2026-08-16 21:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0002_add_kb_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telegram_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("username", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(default="active", max_length=40)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                (
                    "attached_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="OwnerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "color",
                    models.CharField(
                        default="#596623",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Укажите HEX-цвет вида #596623"
                            )
                        ],
                    ),
                ),
                ("emoji", models.CharField(blank=True, max_length=16)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("is_system", models.BooleanField(default=False)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_statuses",
                        to="crm.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TelegramOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=32)),
                (
                    "telegram_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "telegram_username",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("display_name", models.CharField(blank=True, max_length=160)),
                ("registered_at", models.DateField(blank=True, null=True)),
                (
                    "used_since",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("notes", models.TextField(blank=True)),
                ("notes_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("S", "S"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                        ],
                        db_index=True,
                        default="D",
                        max_length=1,
                    ),
                ),
                (
                    "health",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "sim_state",
                    models.CharField(
                        choices=[
                            ("ready", "Готово"),
                            ("attention", "Требует внимания"),
                            ("critical", "Критическая проблема"),
                            ("missing", "Отсутствует"),
                        ],
                        default="missing",
                        max_length=16,
                    ),
                ),
                (
                    "session_state",
                    models.CharField(
                        choices=[
                            ("ready", "Готово"),
                            ("attention", "Требует внимания"),
                            ("critical", "Критическая проблема"),
                            ("missing", "Отсутствует"),
                        ],
                        default="missing",
                        max_length=16,
                    ),
                ),
                (
                    "twofa_state",
                    models.CharField(
                        choices=[
                            ("ready", "Готово"),
                            ("attention", "Требует внимания"),
                            ("critical", "Критическая проблема"),
                            ("missing", "Отсутствует"),
                        ],
                        default="missing",
                        max_length=16,
                    ),
                ),
                (
                    "proxy_state",
                    models.CharField(
                        choices=[
                            ("ready", "Готово"),
                            ("attention", "Требует внимания"),
                            ("critical", "Критическая проблема"),
                            ("missing", "Отсутствует"),
                        ],
                        default="missing",
                        max_length=16,
                    ),
                ),
                ("has_premium", models.BooleanField(default=False)),
                ("is_scam", models.BooleanField(default=False)),
                ("is_blocked", models.BooleanField(default=False)),
                ("session_ciphertext", models.TextField(blank=True)),
                ("twofa_ciphertext", models.TextField(blank=True)),
                ("proxy_ciphertext", models.TextField(blank=True)),
                ("sim_ciphertext", models.TextField(blank=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "last_login_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner_logins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notes_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner_notes_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responsible_owners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owners",
                        to="owners.ownerstatus",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_owners",
                        to="crm.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SavedOwnerFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("query", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_owner_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_owner_filters",
                        to="crm.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="OwnerChannelHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_role", models.CharField(blank=True, max_length=80)),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_history",
                        to="owners.ownerchannel",
                    ),
                ),
                (
                    "new_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="channels_transferred_to",
                        to="owners.telegramowner",
                    ),
                ),
                (
                    "previous_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="channels_transferred_from",
                        to="owners.telegramowner",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="ownerchannel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="channels",
                to="owners.telegramowner",
            ),
        ),
        migrations.AddField(
            model_name="ownerchannel",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_channels",
                to="crm.workspace",
            ),
        ),
        migrations.CreateModel(
            name="OwnerAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_username", models.CharField(blank=True, max_length=160)),
                ("actor_role", models.CharField(blank=True, max_length=80)),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("description", models.CharField(max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="owners.telegramowner",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="telegramowner",
            index=models.Index(
                fields=["workspace", "archived_at", "health"], name="owners_feed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telegramowner",
            index=models.Index(fields=["workspace", "rank"], name="owners_rank_idx"),
        ),
        migrations.AddConstraint(
            model_name="telegramowner",
            constraint=models.UniqueConstraint(
                condition=models.Q(("telegram_id__isnull", False)),
                fields=("workspace", "telegram_id"),
                name="owners_unique_workspace_telegram_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="telegramowner",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone", ""), _negated=True),
                fields=("workspace", "phone"),
                name="owners_unique_workspace_phone",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedownerfilter",
            constraint=models.UniqueConstraint(
                fields=("workspace", "user", "name"), name="owners_unique_saved_filter"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerstatus",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"), name="owners_unique_status_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerchannel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("telegram_id__isnull", False)),
                fields=("workspace", "telegram_id"),
                name="owners_unique_channel_telegram_id",
            ),
        ),
        migrations.AddIndex(
            model_name="ownerauditlog",
            index=models.Index(
                fields=["owner", "-created_at"], name="owners_audit_owner_idx"
            ),
        ),
    ]
