# Generated by Django 4.2.14 on 2026-04-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_auto_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bot_check_detail',
            field=models.TextField(blank=True, help_text='Человекочитаемое объяснение последней проверки прав бота', verbose_name='Детали проверки'),
        ),
    ]
