# Generated by Django 4.2.14 on 2026-04-14 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_join_request_and_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=200, unique=True, verbose_name='Ник клиента')),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='Сколько клиент платит за одну заявку', max_digits=10, verbose_name='Ставка ($) за заявку')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL ссылки')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Деактивирована'), ('paused', 'Приостановлена')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_note', models.CharField(blank=True, max_length=500, verbose_name='Причина деактивации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Ссылка клиента',
                'verbose_name_plural': 'Ссылки клиентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('unassign_reason', models.CharField(blank=True, choices=[('inactivity', 'Неактивность (3 дня)'), ('link_deactivated', 'Ссылка деактивирована'), ('manual', 'Ручное снятие'), ('reassigned', 'Переназначен вручную')], max_length=30)),
                ('last_count_updated_at', models.DateTimeField(blank=True, help_text='Время последнего обновления attracted_count. Используется для проверки неактивности.', null=True)),
                ('client_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='clients.clientlink', verbose_name='Ссылка клиента')),
                ('work_link', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='users.worklink', verbose_name='Рабочая ссылка воркера')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Воркер')),
            ],
            options={
                'verbose_name': 'Назначение ссылки',
                'verbose_name_plural': 'Назначения ссылок',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
