# Generated by Django 4.2.14 on 2026-04-10 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_rateconfig_dailyreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemstats',
            options={'ordering': ['-date'], 'verbose_name': 'Системная статистика', 'verbose_name_plural': 'Системная статистика'},
        ),
        migrations.AlterModelOptions(
            name='userdailystats',
            options={'ordering': ['-date'], 'verbose_name': 'Статистика пользователя', 'verbose_name_plural': 'Статистика пользователей'},
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, unique=True, verbose_name='Дата'),
        ),
    ]
