# Generated by Django 4.2.14 on 2026-08-16 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0016_report_deadline_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeereport",
            name="current_revision",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Текущая версия содержимого"
            ),
        ),
        migrations.CreateModel(
            name="ReportMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        db_index=True, default=1, verbose_name="Версия отчёта"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Позиция"),
                ),
                (
                    "telegram_file_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Telegram file_id"
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        verbose_name="Ключ приватного хранилища",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=32,
                        verbose_name="Тип медиа",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=127, verbose_name="MIME-тип"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя файла"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Размер файла"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ready", "Доступен"), ("failed", "Недоступен")],
                        db_index=True,
                        default="ready",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ошибка сохранения"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="control.employeereport",
                        verbose_name="Отчёт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медиафайл отчёта",
                "verbose_name_plural": "Медиафайлы отчётов",
                "ordering": ["revision", "position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="reportmedia",
            constraint=models.UniqueConstraint(
                fields=("report", "revision", "position"),
                name="uniq_report_media_revision_position",
            ),
        ),
    ]
