# Generated by Django 4.2.14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0017_employeereport_current_revision_reportmedia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialConditionChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("previous_daily_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("new_daily_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("previous_available_balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("new_available_balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("employee_notified_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notified_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performed_financial_condition_changes",
                        to="users.user",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_condition_changes",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изменение финансовых условий",
                "verbose_name_plural": "Изменения финансовых условий",
                "ordering": ["-created_at"],
            },
        ),
    ]
