# Generated by Django 4.2.14 on 2026-04-03 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal label (not sent to users)', max_length=255)),
                ('text', models.TextField(help_text='Message text. Supports HTML parse mode.')),
                ('parse_mode', models.CharField(default='HTML', max_length=10)),
                ('audience', models.CharField(choices=[('all', 'All users'), ('active', 'Active users only'), ('invited', 'Activated via invite key')], default='all', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Broadcast',
                'verbose_name_plural': 'Broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('blocked', 'Bot blocked')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='broadcasts.broadcast')),
            ],
            options={
                'verbose_name': 'Delivery Log',
                'verbose_name_plural': 'Delivery Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
