# Generated by Django 4.2.14 on 2026-04-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='broadcastdeliverylog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Лог доставки', 'verbose_name_plural': 'Логи доставки'},
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='audience',
            field=models.CharField(choices=[('all', 'Все пользователи'), ('active', 'Только активные'), ('invited', 'Активированные по инвайту')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('confirmed', 'Подтверждён'), ('running', 'Отправляется'), ('done', 'Завершён'), ('failed', 'Ошибка')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='broadcastdeliverylog',
            name='status',
            field=models.CharField(choices=[('sent', 'Доставлено'), ('failed', 'Ошибка'), ('blocked', 'Бот заблокирован')], max_length=20),
        ),
    ]
